version: "3.8"

services:
  app:
    container_name: eth-balance-searcher
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "6060:6060"
      - "4000:8000"
    depends_on:
      - redis
    restart: always
    volumes:
      - ./config:/app/config
      - ./.env:/app/.env
    networks:
      - eth
  
  redis:
    image: redis:6-alpine
    container_name: api-redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - eth

networks:
  eth:
    driver: bridge